Repository LarytheLord/Adventurers-Guild, pull requests merged in 2025-08, with the labels that each got.

#39 Added go to top and dark mode toggle button
  app/globals.css
  app/page.tsx
  components/ui/go-to-top.tsx
  components/ui/theme-toggle.tsx
  package-lock.json
  project_improvements.md
Labels: enhancement, good first issue, Gssoc issue, Gssoc Contributer

#38 Add Trusted Partners and Organizations section to Home page and Main page
  app/page.tsx
  tailwind.config.ts
Labels: enhancement, good first issue, Gssoc issue, Gssoc Contributer

#47 ✨ Add client-side search & filtering to quest board with enhanced UI 🔎
  app/home/page.tsx
  components/AdventureFilter.tsx
  components/AdventureSearch.tsx
Labels: Gssoc Contributer, completed

#57 Added proper license link to README
  README.md
Labels: completed
